# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3b60ca8b70a4c9472fb1aa610f0339d1c41fd75fd41b4b219433aa672ea24250bb0096ec4871cb68744fa3560847f12e83e94f51ca8c90e05565fd756b0cd6e

test:
  secret_key_base: 446622b4b67141d42eceddd71a02bdb964b73016a766d1c220780d8ddd33afb3a2018da5d5c43e59cd416a1aadc2e09fafa37dd454636f0c8560d2932a0988f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
